language: node_js

node_js:
  - "10"
  - "8"

after_success:
  - yarn codecov

cache: yarn
branches:
  only:
    - master

jobs:
  include:
    - stage: release
      node_js: "10"
      script:
        - yarn run build
        - yarn semantic-release
