language: node_js
node_js:
  - node

jobs:
  include:
    - stage: release
      script:
        - yarn build
        - yarn semantic-release
      after_script: skip

cache:
  yarn: true
  npm: true

after_script:
  - yarn codecov

branches:
  only:
    - master
